name: fire_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies: 
  flare_flutter: ^1.5.5
  datetime_picker_formfield: ^0.4.1 #date time picker  
  provider: ^3.0.0+1 #provider
  cloud_firestore: ^0.12.9
  firebase_database: ^3.0.5
  keyboard_avoider: ^0.1.2
  firebase_auth: ^0.14.0
  firebase_core: ^0.4.0+8
  google_sign_in: ^4.0.0
  flutter_svg: ^0.14.0
  fluttie: ^0.3.0
  
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/assets/
  fonts:
    - family:  Lobster Two
      fonts:
        - asset: fonts/LobsterTwo-Regular.ttf
